AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaFunctionName:
    Type: String
    Default: TriggerGlueJobLambda

Outputs:
  TriggerGlueJobFunctionArn:
    Description: "ARN da função Lambda TriggerGlueJobFunction"
    Value: !GetAtt TriggerGlueJobFunction.Arn
    Export:
      Name: TriggerGlueJobFunctionArn

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaGlueTriggerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - 'arn:aws:s3:::*'
                  - 'arn:aws:s3:::*/*'
        - PolicyName: LambdaLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:* 

  TriggerGlueJobFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: lambdahandler.handler 
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !ImportValue S3LambdaCodeStorage
        S3Key: 'app/lambdahandler.zip' 
      Runtime: python3.8